### ISSUE TITLE
Wrong default vehicle color

### ISSUE THREAD

**Issue by afdaniele** [duckietown/dt-gui-tools#47]
Vehicle color is `#fff` by default, it should be `null`, so that the robots can retain their original colors by default.

**Comment by light5551** [comment]
https://github.com/duckietown/duckietown-world/commit/370d3b6ad7d50c40e1a243202c1b6ed3ef6f792b#diff-a4b720964a857c4a52a7c6b0467adf8d46c2bcf0ecb4ed173e29e72273991aa8R117 - here is fixed

**Comment by light5551** [comment]
@afdaniele
