### ISSUE TITLE
Add 'family' field to the trafficsign layer

### ISSUE THREAD

**Issue by afdaniele** [duckietown/dt-gui-tools#52]
In `trafficsigns.yaml`, we have only `id` and `type`, we should add also `family` as we have it in `groundtags.yaml`.

**Comment by afdaniele** [comment]
I don't see how that PR fixes this issue.

**Comment by light5551** [comment]
https://github.com/duckietown/duckietown-world/pull/49/files#diff-a4b720964a857c4a52a7c6b0467adf8d46c2bcf0ecb4ed173e29e72273991aa8R88

**Comment by afdaniele** [comment]
Verified.
